name: musicapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  hydrated_bloc: ^10.1.1
  flutter_bloc: ^9.1.1
  path_provider: ^2.1.4
  just_audio: ^0.10.5
  marquee: ^2.3.0
  audio_video_progress_bar: ^2.0.3
  lottie: ^3.3.2
  permission_handler: ^12.0.1
  on_audio_query: ^2.9.0
  provider: ^6.1.5+1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/loginbg.png
    - assets/icon/google.png
    - assets/images/demoimage.png

  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/fonts/Metropolis-Medium.otf
          weight: 400
        - asset: assets/fonts/Metropolis-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Metropolis-Bold.otf
          weight: 700
        - asset: assets/fonts/Metropolis-ExtraBold.otf
          weight: 800
